// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class TestfitnessTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void testKirill180() {
        driver.get("https://lm.skillbox.cc/qa_tester/module03/practice2//qa_tester/module03/practice2/");
        driver.manage().window().setSize(new Dimension(1285, 816));
        driver.findElement(By.name("name")).sendKeys("Kirill");
        driver.findElement(By.name("height")).sendKeys("180");
        driver.findElement(By.name("weight")).click();
        driver.findElement(By.name("weight")).sendKeys("80");
        driver.findElement(By.id("get-offer")).click();
        assertThat(driver.findElement(By.cssSelector(".user-result")).getText(), is("нормальной массе тела"));
        driver.close();
    }
    @Test
    public void testPashok160() {
        driver.get("https://lm.skillbox.cc/qa_tester/module03/practice2//qa_tester/module03/practice2/");
        driver.manage().window().setSize(new Dimension(1285, 816));
        driver.findElement(By.name("name")).click();
        driver.findElement(By.name("name")).sendKeys("пАШОК");
        driver.findElement(By.name("height")).sendKeys("160");
        driver.findElement(By.name("weight")).sendKeys("100");
        driver.findElement(By.id("get-offer")).click();
        assertThat(driver.findElement(By.cssSelector(".user-result")).getText(), is("избыточной массе тела"));
        driver.close();
    }
    @Test
    public void testSergoboss() {
        driver.get("https://lm.skillbox.cc/qa_tester/module03/practice2/");
        driver.manage().window().setSize(new Dimension(1285, 816));
        driver.findElement(By.name("name")).click();
        driver.findElement(By.name("name")).sendKeys("Sergo");
        driver.findElement(By.name("height")).sendKeys("170");
        driver.findElement(By.name("weight")).sendKeys("40");
        driver.findElement(By.id("get-offer")).click();
        assertThat(driver.findElement(By.cssSelector(".user-result")).getText(), is("выраженному дефициту массы тела"));
        driver.close();
    }
}
